version: "3"  
services: # only 2 services
  web:
    build: ./
    ports:
      - "70:70"
    container_name: trivia-webpage
    depends_on:
      - db
    volumes:
      - my-trivia:/var/www/html
     
  db:
    image: mysql:8.0
    container_name: db-mysql
    environment:
     #- MYSQL_HOST=localhost
     #- MYSQL_USER=root
     - MYSQL_PASSWORD=12345
     - MYSQL_ROOT_PASSWORD=12345
     - MYSQL_DATABASE=flaskapp
  #   - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db-1:/var/lib/mysql

volumes:
  db-1:
  my-trivia:
 
  





